use classicmodels;
select lastName from employees;
select lastName, firstName, jobTitle from employees;
select * from employees;
select lastName, firstName, jobTitle from employees where jobTitle = "Sales Rep";
select LastName, firstName, jobTitle, officeCode from employees where jobTitle = "Sales Rep" and officeCode = 1;
select LastName, firstName, jobTitle, officeCode from employees where jobTitle = "Sales Rep" or officeCode = 1;
select lastName, firstName, officeCode from employees where officeCode in(1, 2, 3);
select lastName, firstName, jobTitle from employees where jobTitle <> "Sales Rep";
select lastName, firstName, officeCode from employees where officeCode > 5;
select lastName, firstName, officeCode from employees where officeCode <= 4;
select customerName, country, state from customers where country = "USA" and state = "CA";
select customerName, country, state, creditLimit from customers where country = "USA" and state = "CA" and creditLimit > 100000;
select customerName, country from customers where country = "USA" or "France";
select customerName, country, creditLimit from customers where country in("USA", "France") and creditLimit > 100000;
select officeCode, city, phone, country from offices where country = "USA" or "France";
select officeCode, city, phone, country from offices where not country in("USA", "France");
select orderNumber, customerNumber, status, shippedDate from orders where orderNumber in(10165, 10287, 10310);
select contactLastName, contactFirstName from customers order by contactLastName asc;
select contactLastName, contactFirstName from customers order by contactLastName desc;
select contactLastName, contactFirstName from customers order by contactLastName desc, contactFirstName asc;
select customerNumber, customerName, creditLimit from customers order by creditLimit desc limit 5;
select customerNumber, customerName, creditLimit from customers order by creditLimit asc limit 5;